VseFormuli/VseFormuli/urls.py
from . import settings
from django.contrib import admin
from django.urls import path, include
import subjectscontent.urls
import mainpage.urls
import cinema.urls
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('formulas/', include(subjectscontent.urls)),
    path('', include(mainpage.urls)),
    path('cinema/', include(cinema.urls)),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

VseFormuli/cinema/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.cinema),
    path("addVideo", views.addVideos)
]

VseFormuli/mainpage/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.mainSite),
]

VseFormuli/subjectscontent/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('function', views.function),
    path('', views.formulas),
    path('mathformulas', views.mathformulas),
    path('algebraformulas', views.algebraformulas),
    path('geometryformulas', views.geometryformulas),
    path('physicsformulas', views.physicsformulas),
    path('class', views.some_class.as_view()),
    path('reservation', views.hz),
]

VseFormuli/cinema/models.py
from django.db import models
from django.core.validators import FileExtensionValidator

# Create your models here.
class Video(models.Model):
    video = models.FileField("file", upload_to='media/', validators=[FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv', 'wmv'])])  # noqa: F821
    title = models.CharField("title", max_length=50)
    preview = models.ImageField("preview", upload_to='media/', validators=[FileExtensionValidator(allowed_extensions=['jpg', 'png', 'PNG', 'webp'])])
    CATEGORIES = {'Math' :'Math', 'Geometry' : 'Geometry', 'Physics' : 'Physics', 'Algebra' : 'Algebra'}
    category = models.CharField("category", max_length=50, default="Math", choices=CATEGORIES)
    class Meta():
        verbose_name = "Video"
        verbose_name_plural = "Videos"

VseFormuli/subjectscontent/models.py
from django.db import models

# Create your models here.
class MenuItem(models.Model):
    name = models.CharField(max_length=255)
    price = models.IntegerField()

class Reservation(models.Model):
    firstName = models.CharField(max_length=255)
    lastName = models.CharField(max_length=255)
    guestCount = models.IntegerField()
    reservationTime = models.DateField(auto_now=True)
    comments = models.CharField(max_length=1000)

VseFormuli/cinema/forms.py
from django.forms import ModelForm, TextInput
from .models import Video

class addVideoForm(ModelForm):
    class Meta:
        model = Video
        fields = "__all__"
        widgets = {
            'title' : TextInput(attrs={'placeholder' : 'Введите название'})
        }
        

VseFormuli/subjectscontent/forms.py
from django import forms
from .models import Reservation

class ReservationForm(forms.ModelForm):
    class Meta:
        model = Reservation
        fields = '__all__'

VseFormuli/cinema/views.py
from django.shortcuts import render
from .models import Video
from .forms import addVideoForm

# Create your views here.
def cinema(request):
    videos = Video.objects.all()
    return render(request, "cinema/cinema.html", context={"videos":videos})
def addVideos(request):
    form = addVideoForm()
    if request.method == "POST":
        form = addVideoForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return cinema(request)
    return render(request, "cinema/addVideo.html", {"form" : form})

VseFormuli/mainpage/views.py
from django.shortcuts import render

# Create your views here.
def mainSite(request):
    return render(request, template_name="main.html")

VseFormuli/subjectscontent/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views import View
from .forms import ReservationForm

# Create your views here.
def formulas(request):
    return render(request,template_name='index.html')
def mathformulas(request):
    return render(request,template_name='math.html')
def algebraformulas(request):
    return render(request,template_name='algebra.html')
def geometryformulas(request):
    return render(request,template_name='geometry.html')
def physicsformulas(request):
    return render(request,template_name='physics.html')
#studying
def hz(request):
    form = ReservationForm()
    if request.method == 'POST':
        form = ReservationForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponse("Success")
    return render(request, 'hz.html', {'form' : form })    

def function(request):
    return HttpResponse("Hallo")
class some_class(View):
    def get(self, request):
        return HttpResponse("Goyda")

VseFormuli/cinema/templates/cinema/addVideo.html
{%extends 'cinema/cinema.html'%}
{% load static%}
{%block content%}
<link rel="stylesheet" href="{%static 'cinema/css/addVideo.css'%}">
<div class="addVideo">
    <h2 style="text-align: center;">Добавить видева</h2>
    <form method = "POST" enctype="multipart/form-data">
        {% csrf_token%}
        <label for="id_video">Файл видео: </label>
        {{form.video}}
        <label for="id_preview">Файл превью: </label>
        {{form.preview}}
        <label for="id_name">Название: </label>
        {{form.title}}
        <label for="id_category">Категория: </label>
        {{form.category}}
        <button type="submit">
            Добавить
        </button>
    </form>
</div>
{%endblock%}

VseFormuli/cinema/templates/cinema/cinema.html
<!DOCTYPE html>
<html lang="ru">
<head>
    {%load static%}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{%static 'mainpage/css/mainstyle.css'%}">
    <link rel="stylesheet" href="{%static 'subjectscontent/css/base.css'%}">
    <link rel="stylesheet" href="{%static 'cinema/css/cinema.css'%}">
    <title>Cinema</title>
</head>
<body><a href=".."><img src = "https://cdn.alfacrm.pro/favicon-48.png" class="basereturn" style="top: 2%;height: 8%;width: 4%;"></a>
    {% block content%}
    <form action="">
        <input type="search" name="" id="" placeholder="Введите название видева">
        <input type="submit" value = "Найти" name="" id="">
    </form>
    <a href="addVideo"><img src="{%static 'cinema/pictures/addVideoButton.svg'%}" alt="" class="addVideoButton" style="right: 61%; top: -1.5%; filter: invert(90%); height: 17.5%;"></a>
    <div class="column">
        <div class="category">
            <h6>Математика 1-6</h6>
        </div>
        <div class="row">
            {% for i in videos %}
                <a href="{{ i.video.url }}" target="_blank"><img src="{{ i.preview.url }}"></a>
                <span>{{ i.title }}</span>
            {% endfor %}
        </div>
        <div class="category">
            <h6>Геометрия 7-11</h6>
        </div>
        <div class="row">
            
        </div>
        <div class="category">
            <h6>Алгебра 7-11</h6>
        </div>
        <div class="row">
            
        </div>
        <div class="category">
            <h6>Физика 7-11</h6>
        </div>
        <div class="row">
            
        </div>
    </div>
    {% endblock %}
</body>
</html>

VseFormuli/mainpage/templates/main.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {%load static%}
  <link rel="stylesheet" href="{%static 'mainpage\css\mainstyle.css'%}">
  <title>Главная</title>
</head>
<body>
  <div class= "main">
    <h1>VseFormuli</h1>
    <ul>
      <li><a href="formulas/">Main</a></li>
      <li><a href="cinema">Cinema</a></li> <!--Сделать приложуху-->
      <li><a href="tasks">Problems set</a></li> <!--Сделать приложуху-->
    </ul>
  </div>
</body>
</html>

VseFormuli/subjectscontent/templates/algebra.html
{%extends 'categorybase.html'%}
{%load static%}
{%block rows%}
<tr>
    <td>
        <p>Sorry, the picture is not available at the moment</p>
    </td>
    <td>
        <p>The theorem of Pythagoras</p>
    </td>
</tr>
{%endblock%}

VseFormuli/subjectscontent/templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {%load static%}
    <link rel = "stylesheet" href="{%static 'subjectscontent\css\base.css'%}">
    {%block connect%}
    {%endblock%}
    <title>VseFormuli</title> <!--.ru-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Gidole&display=swap" rel="stylesheet">
</head>
<body>
    <aside id="sidebar">
        <a href=".." class="basereturn"><img src = "https://cdn.alfacrm.pro/favicon-48.png" width = "20%" class = "basereturn"></a>
        <h1><a href="." class="Main">На главную</a></h1>
        <nav>
            <ul>
                <li><a href = "mathformulas">Математика 1-6</a></li>
                <li><a href = "algebraformulas">Алгебра 7-11</a></li>
                <li><a href = "geometryformulas">Геометрия 7-11</a></li>
                <li><a href = "physicsformulas">Физике 7-11</a></li>
            </ul>
        </nav>
        <footer>
            <img src = "{%static 'subjectscontent\pictures\settingsIcon.png'%}" style="right: 71%; position: absolute; width: 20%;" class = "settings">
            <a href = "" style="text-align: center; right: 9%; position: absolute; width: 50%;" class="haveQuestions">Возникли вопросы? - напишите в тех.поддержку</a>
        </footer>
    </aside>
    <main>
        <button onClick="OpenClose('pcbutton')" id = "openclosebutton" class="pcbutton"><img src="{%static 'subjectscontent\pictures\toggleMenu.png'%}" class="toggleMenu"></button>
        <form action="">
            <input type="search" name="" id="" placeholder="Введите формулу">
            <input type="submit" value = "Найти" name="" id="">
        </form>
    {%block content%}
    {%endblock%}
    </main>
    <button onClick="OpenClose('mobileButton')" id = "openclosebutton" class="mobileButton"><img src="{%static 'subjectscontent\pictures\toggleMenu.png'%}" class="toggleMenu"></button>
    <script>
        var isСlosed = false;
        function OpenClose(buttonclicked) {
            isСlosed = !isСlosed;
            const main = document.querySelectorAll("main");
            if(isСlosed){
                if(buttonclicked == "mobileButton"){
                document.getElementsByClassName("toggleMenu")[1].style.transform = "rotate(180deg)";
                    document.getElementById("sidebar").style.display = "block";
                    main.forEach(element => { element.style.display = 'none'; });
                }
                else{
                    document.getElementById("sidebar").style.display = "none";
                    document.getElementsByClassName("toggleMenu")[0].style.transform = "rotate(0deg)";
                }
            }
            else{
                if(buttonclicked == "mobileButton"){
                document.getElementsByClassName("toggleMenu")[1].style.transform = "rotate(0deg)";
                    document.getElementById("sidebar").style.display = "none";
                    main.forEach(element => { element.style.display = 'flex'; });
                }
                else{
                document.getElementsByClassName("toggleMenu")[0].style.transform = "rotate(180deg)";
                    document.getElementById("sidebar").style.display = "block";
                }
            }
        }
    </script>
</body>
</html>

VseFormuli/subjectscontent/templates/categorybase.html
{%extends 'base.html'%}
{%load static%}
{%block connect%}
    <link rel = "stylesheet" href="{%static 'subjectscontent\css\category.css'%}">
{%endblock%}
{%block content%}
            <table>
                <thead>
                    <th>
                        Формула
                    </th>
                    <th>
                        Применение
                    </th>
                </thead>
                <tbody> 
                    {%block rows%}
                    {%endblock%}
                </tbody>
            </table>
{%endblock%}

VseFormuli/subjectscontent/templates/geometry.html
{%extends 'categorybase.html'%}
{%load static%}
{%block rows%}
<tr>
    <td>
        <p>Sorry, the picture is not available at the moment</p>
    </td>
    <td>
        <p>Bissectrisa is such a mouse which cuts angles on two equal</p>
    </td>
</tr>
{%endblock%}

VseFormuli/subjectscontent/templates/hz.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save</button>
    </form>
</body>
</html>

VseFormuli/subjectscontent/templates/index.html
{%extends 'base.html'%}

VseFormuli/subjectscontent/templates/math.html
{%extends 'categorybase.html'%}
{%load static%}
{%block rows%}
<tr>
    <td>
        <img src="{%static 'subjectscontent\pictures\formula.jpg'%}">
    </td>
    <td>
        <p>asdfgfadsfgg</p>
    </td>
</tr>
{%endblock%}

VseFormuli/subjectscontent/templates/physics.html
{%extends 'categorybase.html'%}
{%load static%}
{%block rows%}
<tr>
    <td>
        <p>Sorry, the picture is not available at the moment</p>
    </td>
    <td>
        <p>The rule of Buravchik</p>
    </td>
</tr>
{%endblock%}